theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  plausible: www.ouest-herault-sante.fr
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
  organizations:
    index:
      taxonomies:
        display: false